on:
  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main", "master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  cargo-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: cargo-build
        run: cargo build
  nix-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: nix-build
        run: |
          nix flake test
          nix build
          